# Generated by Django 4.0.6 on 2024-03-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_program_rank_camper_program_group_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanksheetline',
            name='max_points',
            field=models.IntegerField(default=-1),
        ),
    ]
