# Generated by Django 4.0.6 on 2024-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_blanksheetline_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanksheetline',
            name='group_type',
            field=models.CharField(choices=[('bunk', 'bunk'), ('learning_class', 'learning_class')], default='bunk', max_length=30),
        ),
    ]
