# Generated by Django 4.0.6 on 2024-03-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_alter_blanksheetline_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanksheetline',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blank_sheet', to='points.program'),
        ),
    ]
