# Generated by Django 4.0.6 on 2024-03-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_blanksheetline_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='use_generic_sheet',
            field=models.BooleanField(default=True),
        ),
    ]
