# Generated by Django 4.0.6 on 2024-07-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_markedsheet_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanksheetline',
            name='checklist_dict',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blanksheetline',
            name='is_checklist_dict_updated',
            field=models.BooleanField(default=False),
        ),
    ]
