# Generated by Django 4.0.6 on 2024-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_blanksheetline_checklist_dict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedsheetline',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
