# Generated by Django 5.0.6 on 2024-07-29 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0012_markedsheetline_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OverallPointsCamper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='camper',
            name='total_bunk_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camper',
            name='total_class_points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WeeklyChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(blank=True, null=True)),
                ('chart', models.JSONField(blank=True, null=True)),
                ('camper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_chart', to='points.camper')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_chart', to='points.group')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_chart', to='points.program')),
            ],
            options={
                'unique_together': {('program', 'week', 'group', 'camper')},
            },
        ),
    ]
