services:
  - type: web
    name: cgifth-test
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn th.wsgi:application
    runtime: python-3.11
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: cgifth-test.onrender.com
